#!/bin/bash

echo "🔍 배차 확정 버튼 표시 조건 확인"
echo "================================"
echo ""

echo "1️⃣  최적화 결과 확인..."
echo ""
echo "   배차 확정 버튼이 보이려면:"
echo "   ✅ '배차 최적화' 버튼을 먼저 클릭해야 합니다"
echo "   ✅ 최적화가 완료되어야 합니다"
echo "   ✅ optimizationResult가 있어야 합니다"
echo ""

echo "2️⃣  UI 흐름:"
echo ""
echo "   Step 1: 주문 관리에서 주문 선택 (체크박스)"
echo "           ↓"
echo "   Step 2: 'AI 배차' 버튼 클릭"
echo "           ↓"
echo "   Step 3: 최적화 페이지로 이동"
echo "           ↓"
echo "   Step 4: '배차 최적화' 버튼 클릭 ⭐"
echo "           ↓"
echo "           (30-60초 대기)"
echo "           ↓"
echo "   Step 5: 최적화 결과 표시"
echo "           - 차량별 배차 내역"
echo "           - GPS 위치"
echo "           - 실제 거리/시간"
echo "           ↓"
echo "   Step 6: '배차 확정' 버튼 나타남! ⭐⭐⭐"
echo "           (초록색 버튼, 최적화 실행 버튼 옆)"
echo ""

echo "3️⃣  버튼 위치:"
echo ""
echo "   화면 상단:"
echo "   ┌────────────────────────────────────┐"
echo "   │  [배차 최적화]  [배차 확정] ← 여기! │"
echo "   └────────────────────────────────────┘"
echo ""
echo "   - 배차 최적화 버튼 (파란색) 오른쪽"
echo "   - 초록색 버튼"
echo "   - 아이콘: ✓ (체크)"
echo ""

echo "4️⃣  버튼이 안 보이는 경우:"
echo ""
echo "   ❌ 최적화를 아직 실행하지 않음"
echo "      → '배차 최적화' 버튼을 먼저 클릭하세요"
echo ""
echo "   ❌ 최적화가 실패함"
echo "      → 에러 메시지 확인"
echo "      → 주문/차량이 있는지 확인"
echo ""
echo "   ❌ 최적화 진행 중"
echo "      → 30-60초 대기"
echo "      → 'Loading...' 표시 확인"
echo ""

echo "5️⃣  확인 방법:"
echo ""
echo "   브라우저에서 F12 (개발자 도구)"
echo "   → Console 탭"
echo "   → 다음 명령 입력:"
echo ""
echo "   localStorage.getItem('optimization_result')"
echo ""
echo "   결과가 null이면: 최적화를 실행하지 않음"
echo "   결과가 있으면: Frontend 렌더링 문제"
echo ""

echo "6️⃣  임시저장 배차 확정 (대안):"
echo ""
echo "   이미 임시저장 배차가 9건 있습니다!"
echo "   배차 관리 페이지에서 직접 확정할 수 있습니다:"
echo ""
echo "   1. http://139.150.11.99/dispatches 접속"
echo "   2. 임시저장 배차 목록 표시됨"
echo "   3. 확정하려는 배차 선택 (체크박스)"
echo "   4. '선택 확정' 버튼 클릭"
echo ""

echo "✅ 가이드 완료!"
echo ""
echo "💡 권장 순서:"
echo "   1. 새로운 최적화 실행"
echo "   2. 최적화 페이지에서 '배차 확정' 버튼 확인"
echo "   3. 또는 배차 관리 페이지에서 기존 임시저장 배차 확정"
