#!/bin/bash
# Initialize fresh database with all tables

echo "=========================================="
echo "Fresh Database Initialization"
echo "=========================================="
echo ""

echo "📋 Commands to run on server:"
echo ""
echo "cd /root/uvis"
echo ""
echo "# Check migration history"
echo "docker-compose exec backend alembic history | head -50"
echo ""
echo "# Check for baseline migration"
echo "docker-compose exec backend ls -la /app/alembic/versions/ | grep baseline"
echo ""
echo "# Option 1: Use Python to create all tables directly (RECOMMENDED)"
echo "docker-compose exec backend python -c \""
echo "from app.models.base import Base"
echo "from app.core.database import engine"
echo "import app.models"
echo ""
echo "print('Creating all tables...')"
echo "Base.metadata.create_all(bind=engine)"
echo "print('✅ All tables created!')"
echo "\""
echo ""
echo "# Mark database as up-to-date with current migration"
echo "docker-compose exec backend alembic stamp head"
echo ""
echo "# Verify tables were created"
echo "docker-compose exec db psql -U uvis_user -d uvis_db -c \"\\dt\""
echo ""
echo "=========================================="
