"""add phone field to users

Revision ID: a6eb2e22dbd2
Revises: baseline_20260206
Create Date: 2026-02-06 11:26:26.844228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a6eb2e22dbd2'
down_revision: Union[str, Sequence[str], None] = 'baseline_20260206'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('meta_data', sa.JSON(), nullable=True, comment='추가 메타데이터 (JSON)'))
    op.drop_column('notifications', 'notification_metadata')
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True, comment='전화번호'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone')
    op.add_column('notifications', sa.Column('notification_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='추가 메타데이터 (JSON)'))
    op.drop_column('notifications', 'meta_data')
    # ### end Alembic commands ###
