"""Initial migration - create all tables

Revision ID: a995c798829a
Revises: 
Create Date: 2026-01-27 14:09:34.130336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a995c798829a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('band_chat_rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False, comment='채팅방 이름'),
    sa.Column('band_url', sa.String(length=500), nullable=False, comment='밴드 URL'),
    sa.Column('description', sa.Text(), nullable=True, comment='설명'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='활성화 여부'),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True, comment='마지막 메시지 전송 시간'),
    sa.Column('total_messages', sa.Integer(), nullable=True, comment='총 메시지 수'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='수정일시'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_band_chat_rooms_id'), 'band_chat_rooms', ['id'], unique=False)
    op.create_table('clients',
    sa.Column('code', sa.String(length=50), nullable=False, comment='거래처코드'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='거래처명'),
    sa.Column('client_type', sa.Enum('PICKUP', 'DELIVERY', 'BOTH', name='clienttype'), nullable=False, comment='상차/하차 구분'),
    sa.Column('address', sa.String(length=500), nullable=False, comment='기본 주소'),
    sa.Column('address_detail', sa.String(length=200), nullable=True, comment='상세 주소'),
    sa.Column('latitude', sa.Float(), nullable=True, comment='위도'),
    sa.Column('longitude', sa.Float(), nullable=True, comment='경도'),
    sa.Column('geocoded', sa.Boolean(), nullable=False, comment='지오코딩 완료 여부'),
    sa.Column('geocode_error', sa.Text(), nullable=True, comment='지오코딩 오류 메시지'),
    sa.Column('pickup_start_time', sa.String(length=5), nullable=True, comment='상차가능시작시간(HH:MM)'),
    sa.Column('pickup_end_time', sa.String(length=5), nullable=True, comment='상차가능종료시간(HH:MM)'),
    sa.Column('delivery_start_time', sa.String(length=5), nullable=True, comment='하차가능시작시간(HH:MM)'),
    sa.Column('delivery_end_time', sa.String(length=5), nullable=True, comment='하차가능종료시간(HH:MM)'),
    sa.Column('has_forklift', sa.Boolean(), nullable=False, comment='지게차 유무'),
    sa.Column('loading_time_minutes', sa.Integer(), nullable=False, comment='평균 상하차 소요시간(분)'),
    sa.Column('contact_person', sa.String(length=100), nullable=True, comment='담당자명'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='전화번호'),
    sa.Column('notes', sa.Text(), nullable=True, comment='특이사항'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='사용 여부'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_code'), 'clients', ['code'], unique=True)
    op.create_table('drivers',
    sa.Column('code', sa.String(length=50), nullable=False, comment='기사코드'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='기사명'),
    sa.Column('phone', sa.String(length=20), nullable=False, comment='전화번호'),
    sa.Column('emergency_contact', sa.String(length=20), nullable=True, comment='비상연락처'),
    sa.Column('work_start_time', sa.String(length=5), nullable=False, comment='근무시작시간(HH:MM)'),
    sa.Column('work_end_time', sa.String(length=5), nullable=False, comment='근무종료시간(HH:MM)'),
    sa.Column('max_work_hours', sa.Integer(), nullable=False, comment='최대 근무시간'),
    sa.Column('license_number', sa.String(length=50), nullable=True, comment='운전면허번호'),
    sa.Column('license_type', sa.String(length=20), nullable=True, comment='면허 종류'),
    sa.Column('notes', sa.Text(), nullable=True, comment='특이사항'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='사용 여부'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drivers_code'), 'drivers', ['code'], unique=True)
    op.create_table('notices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False, comment='공지사항 제목'),
    sa.Column('content', sa.Text(), nullable=False, comment='공지사항 내용'),
    sa.Column('author', sa.String(length=100), nullable=False, comment='작성자'),
    sa.Column('image_url', sa.String(length=500), nullable=True, comment='첨부 이미지 URL'),
    sa.Column('is_important', sa.Boolean(), nullable=True, comment='중요 공지 여부'),
    sa.Column('views', sa.Integer(), nullable=True, comment='조회수'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='활성화 여부'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='수정일시'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notices_id'), 'notices', ['id'], unique=False)
    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False, comment='발주서 제목'),
    sa.Column('content', sa.Text(), nullable=True, comment='발주 내용'),
    sa.Column('image_urls', sa.Text(), nullable=True, comment='첨부 이미지 URL 목록 (JSON 배열, 최대 5개)'),
    sa.Column('author', sa.String(length=100), nullable=False, comment='작성자'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='활성화 여부'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='수정일시'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_orders_id'), 'purchase_orders', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='사용자명'),
    sa.Column('email', sa.String(length=100), nullable=False, comment='이메일'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='해시된 비밀번호'),
    sa.Column('full_name', sa.String(length=100), nullable=True, comment='전체 이름'),
    sa.Column('role', sa.Enum('ADMIN', 'DISPATCHER', 'DRIVER', 'VIEWER', name='userrole'), nullable=False, comment='사용자 역할'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='활성 상태'),
    sa.Column('is_superuser', sa.Boolean(), nullable=False, comment='슈퍼유저 여부'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='수정일시'),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True, comment='마지막 로그인'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('uvis_access_keys',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('serial_key', sa.String(length=50), nullable=False, comment='업체 인증키'),
    sa.Column('access_key', sa.String(length=100), nullable=False, comment='실시간 인증키'),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='발급 시간'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='만료 시간 (발급 후 5분)'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='활성화 여부'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='수정일시'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_uvis_access_key_active', 'uvis_access_keys', ['is_active'], unique=False)
    op.create_index('idx_uvis_access_key_expires', 'uvis_access_keys', ['expires_at'], unique=False)
    op.create_index(op.f('ix_uvis_access_keys_id'), 'uvis_access_keys', ['id'], unique=False)
    op.create_table('uvis_api_logs',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('api_type', sa.String(length=20), nullable=False, comment='API 유형 (auth/gps/temperature)'),
    sa.Column('method', sa.String(length=10), nullable=False, comment='HTTP 메서드'),
    sa.Column('url', sa.Text(), nullable=False, comment='요청 URL'),
    sa.Column('request_params', sa.Text(), nullable=True, comment='요청 파라미터 (JSON)'),
    sa.Column('response_status', sa.Integer(), nullable=True, comment='응답 상태 코드'),
    sa.Column('response_data', sa.Text(), nullable=True, comment='응답 데이터 (JSON)'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='에러 메시지'),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True, comment='실행 시간 (ms)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='생성일시'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_uvis_log_created', 'uvis_api_logs', ['created_at'], unique=False)
    op.create_index('idx_uvis_log_type', 'uvis_api_logs', ['api_type'], unique=False)
    op.create_index(op.f('ix_uvis_api_logs_id'), 'uvis_api_logs', ['id'], unique=False)
    op.create_table('vehicles',
    sa.Column('code', sa.String(length=50), nullable=False, comment='차량코드'),
    sa.Column('plate_number', sa.String(length=20), nullable=False, comment='차량번호'),
    sa.Column('vehicle_type', sa.Enum('FROZEN', 'REFRIGERATED', 'DUAL', 'AMBIENT', name='vehicletype'), nullable=False, comment='온도대 구분'),
    sa.Column('uvis_device_id', sa.String(length=100), nullable=True, comment='UVIS 단말기 ID'),
    sa.Column('uvis_enabled', sa.Boolean(), nullable=False, comment='UVIS 연동 여부'),
    sa.Column('max_pallets', sa.Integer(), nullable=False, comment='최대 팔레트 수'),
    sa.Column('max_weight_kg', sa.Float(), nullable=False, comment='최대 적재중량(kg)'),
    sa.Column('max_volume_cbm', sa.Float(), nullable=True, comment='최대 용적(CBM)'),
    sa.Column('tonnage', sa.Float(), nullable=False, comment='톤수'),
    sa.Column('length_m', sa.Float(), nullable=True, comment='적재함 길이(m)'),
    sa.Column('width_m', sa.Float(), nullable=True, comment='적재함 너비(m)'),
    sa.Column('height_m', sa.Float(), nullable=True, comment='적재함 높이(m)'),
    sa.Column('driver_name', sa.String(length=100), nullable=True, comment='운전자명'),
    sa.Column('driver_phone', sa.String(length=20), nullable=True, comment='운전자 연락처'),
    sa.Column('min_temp_celsius', sa.Float(), nullable=True, comment='최저 온도(°C)'),
    sa.Column('max_temp_celsius', sa.Float(), nullable=True, comment='최고 온도(°C)'),
    sa.Column('fuel_efficiency_km_per_liter', sa.Float(), nullable=True, comment='연비(km/L)'),
    sa.Column('fuel_cost_per_liter', sa.Float(), nullable=True, comment='리터당 연료비'),
    sa.Column('status', sa.Enum('AVAILABLE', 'IN_USE', 'MAINTENANCE', 'OUT_OF_SERVICE', name='vehiclestatus'), nullable=False, comment='차량 상태'),
    sa.Column('garage_address', sa.String(length=500), nullable=True, comment='차고지 주소'),
    sa.Column('garage_latitude', sa.Float(), nullable=True, comment='차고지 위도'),
    sa.Column('garage_longitude', sa.Float(), nullable=True, comment='차고지 경도'),
    sa.Column('notes', sa.Text(), nullable=True, comment='특이사항'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='사용 여부'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plate_number'),
    sa.UniqueConstraint('uvis_device_id')
    )
    op.create_index(op.f('ix_vehicles_code'), 'vehicles', ['code'], unique=True)
    op.create_table('dispatches',
    sa.Column('dispatch_number', sa.String(length=50), nullable=False, comment='배차번호'),
    sa.Column('dispatch_date', sa.Date(), nullable=False, comment='배차일자'),
    sa.Column('vehicle_id', sa.Integer(), nullable=False, comment='차량 ID'),
    sa.Column('driver_id', sa.Integer(), nullable=True, comment='기사 ID'),
    sa.Column('total_orders', sa.Integer(), nullable=False, comment='총 주문 건수'),
    sa.Column('total_pallets', sa.Integer(), nullable=False, comment='총 팔레트 수'),
    sa.Column('total_weight_kg', sa.Float(), nullable=False, comment='총 중량(kg)'),
    sa.Column('total_distance_km', sa.Float(), nullable=True, comment='총 주행거리(km)'),
    sa.Column('empty_distance_km', sa.Float(), nullable=True, comment='공차거리(km)'),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=True, comment='예상 소요시간(분)'),
    sa.Column('estimated_cost', sa.Float(), nullable=True, comment='예상 비용'),
    sa.Column('status', sa.Enum('DRAFT', 'CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='dispatchstatus'), nullable=False, comment='배차 상태'),
    sa.Column('optimization_score', sa.Float(), nullable=True, comment='최적화 점수'),
    sa.Column('ai_metadata', sa.JSON(), nullable=True, comment='AI 배차 메타데이터'),
    sa.Column('notes', sa.Text(), nullable=True, comment='특이사항'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispatches_dispatch_date'), 'dispatches', ['dispatch_date'], unique=False)
    op.create_index(op.f('ix_dispatches_dispatch_number'), 'dispatches', ['dispatch_number'], unique=True)
    op.create_table('orders',
    sa.Column('order_number', sa.String(length=50), nullable=False, comment='주문번호'),
    sa.Column('order_date', sa.Date(), nullable=False, comment='주문일자'),
    sa.Column('temperature_zone', sa.Enum('FROZEN', 'REFRIGERATED', 'AMBIENT', name='temperaturezone'), nullable=False, comment='온도대 구분'),
    sa.Column('pickup_client_id', sa.Integer(), nullable=True, comment='상차 거래처 ID'),
    sa.Column('delivery_client_id', sa.Integer(), nullable=True, comment='하차 거래처 ID'),
    sa.Column('pickup_address', sa.String(length=500), nullable=True, comment='상차 주소'),
    sa.Column('pickup_address_detail', sa.String(length=200), nullable=True, comment='상차 상세주소'),
    sa.Column('pickup_latitude', sa.Float(), nullable=True, comment='상차 위도'),
    sa.Column('pickup_longitude', sa.Float(), nullable=True, comment='상차 경도'),
    sa.Column('delivery_address', sa.String(length=500), nullable=True, comment='하차 주소'),
    sa.Column('delivery_address_detail', sa.String(length=200), nullable=True, comment='하차 상세주소'),
    sa.Column('delivery_latitude', sa.Float(), nullable=True, comment='하차 위도'),
    sa.Column('delivery_longitude', sa.Float(), nullable=True, comment='하차 경도'),
    sa.Column('pallet_count', sa.Integer(), nullable=False, comment='팔레트 수'),
    sa.Column('weight_kg', sa.Float(), nullable=False, comment='중량(kg)'),
    sa.Column('volume_cbm', sa.Float(), nullable=True, comment='용적(CBM)'),
    sa.Column('product_name', sa.String(length=200), nullable=True, comment='품목명'),
    sa.Column('product_code', sa.String(length=100), nullable=True, comment='품목코드'),
    sa.Column('pickup_start_time', sa.Time(), nullable=True, comment='상차 시작시간'),
    sa.Column('pickup_end_time', sa.Time(), nullable=True, comment='상차 종료시간'),
    sa.Column('delivery_start_time', sa.Time(), nullable=True, comment='하차 시작시간'),
    sa.Column('delivery_end_time', sa.Time(), nullable=True, comment='하차 종료시간'),
    sa.Column('requested_delivery_date', sa.Date(), nullable=True, comment='희망 배송일'),
    sa.Column('priority', sa.Integer(), nullable=False, comment='우선순위(1:높음 ~ 10:낮음)'),
    sa.Column('requires_forklift', sa.Boolean(), nullable=False, comment='지게차 필요 여부'),
    sa.Column('is_stackable', sa.Boolean(), nullable=False, comment='적재 가능 여부'),
    sa.Column('status', sa.Enum('PENDING', 'ASSIGNED', 'IN_TRANSIT', 'DELIVERED', 'CANCELLED', name='orderstatus'), nullable=False, comment='주문 상태'),
    sa.Column('notes', sa.Text(), nullable=True, comment='특이사항'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['delivery_client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['pickup_client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)
    op.create_table('vehicle_gps_logs',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('vehicle_id', sa.Integer(), nullable=True, comment='차량 ID'),
    sa.Column('tid_id', sa.String(length=11), nullable=False, comment='단말기 ID'),
    sa.Column('bi_date', sa.String(length=8), nullable=False, comment='날짜 (YYYYMMDD)'),
    sa.Column('bi_time', sa.String(length=6), nullable=False, comment='시간 (HHMMSS)'),
    sa.Column('cm_number', sa.String(length=30), nullable=True, comment='차량번호'),
    sa.Column('bi_turn_onoff', sa.String(length=3), nullable=True, comment='시동 on/off'),
    sa.Column('bi_x_position', sa.String(length=10), nullable=False, comment='위도'),
    sa.Column('bi_y_position', sa.String(length=10), nullable=False, comment='경도'),
    sa.Column('bi_gps_speed', sa.Integer(), nullable=True, comment='속도 (km/h)'),
    sa.Column('latitude', sa.Float(), nullable=True, comment='위도 (Float)'),
    sa.Column('longitude', sa.Float(), nullable=True, comment='경도 (Float)'),
    sa.Column('is_engine_on', sa.Boolean(), nullable=True, comment='시동 상태'),
    sa.Column('speed_kmh', sa.Integer(), nullable=True, comment='속도 (km/h)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='수정일시'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_vehicle_gps_created', 'vehicle_gps_logs', ['created_at'], unique=False)
    op.create_index('idx_vehicle_gps_date_time', 'vehicle_gps_logs', ['bi_date', 'bi_time'], unique=False)
    op.create_index('idx_vehicle_gps_tid', 'vehicle_gps_logs', ['tid_id'], unique=False)
    op.create_index('idx_vehicle_gps_vehicle_id', 'vehicle_gps_logs', ['vehicle_id'], unique=False)
    op.create_index(op.f('ix_vehicle_gps_logs_id'), 'vehicle_gps_logs', ['id'], unique=False)
    op.create_index(op.f('ix_vehicle_gps_logs_tid_id'), 'vehicle_gps_logs', ['tid_id'], unique=False)
    op.create_table('vehicle_temperature_logs',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('vehicle_id', sa.Integer(), nullable=True, comment='차량 ID'),
    sa.Column('off_key', sa.String(length=7), nullable=True, comment='고객 코드'),
    sa.Column('tid_id', sa.String(length=11), nullable=False, comment='단말기 ID'),
    sa.Column('tpl_date', sa.String(length=8), nullable=False, comment='날짜 (YYYYMMDD)'),
    sa.Column('tpl_time', sa.String(length=6), nullable=False, comment='시간 (HHMMSS)'),
    sa.Column('cm_number', sa.String(length=30), nullable=True, comment='차량번호'),
    sa.Column('tpl_x_position', sa.String(length=10), nullable=True, comment='위도'),
    sa.Column('tpl_y_position', sa.String(length=10), nullable=True, comment='경도'),
    sa.Column('tpl_signal_a', sa.Integer(), nullable=True, comment="A 온도 부호 (0='+', 1='-')"),
    sa.Column('tpl_degree_a', sa.String(length=5), nullable=True, comment='A 온도값'),
    sa.Column('temperature_a', sa.Float(), nullable=True, comment='A 온도 (℃)'),
    sa.Column('tpl_signal_b', sa.Integer(), nullable=True, comment="B 온도 부호 (0='+', 1='-')"),
    sa.Column('tpl_degree_b', sa.String(length=5), nullable=True, comment='B 온도값'),
    sa.Column('temperature_b', sa.Float(), nullable=True, comment='B 온도 (℃)'),
    sa.Column('latitude', sa.Float(), nullable=True, comment='위도 (Float)'),
    sa.Column('longitude', sa.Float(), nullable=True, comment='경도 (Float)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='수정일시'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_vehicle_temp_created', 'vehicle_temperature_logs', ['created_at'], unique=False)
    op.create_index('idx_vehicle_temp_date_time', 'vehicle_temperature_logs', ['tpl_date', 'tpl_time'], unique=False)
    op.create_index('idx_vehicle_temp_tid', 'vehicle_temperature_logs', ['tid_id'], unique=False)
    op.create_index('idx_vehicle_temp_vehicle_id', 'vehicle_temperature_logs', ['vehicle_id'], unique=False)
    op.create_index(op.f('ix_vehicle_temperature_logs_id'), 'vehicle_temperature_logs', ['id'], unique=False)
    op.create_index(op.f('ix_vehicle_temperature_logs_tid_id'), 'vehicle_temperature_logs', ['tid_id'], unique=False)
    op.create_table('band_message_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dispatch_id', sa.Integer(), nullable=False, comment='배차 ID'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='스케줄 활성화'),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False, comment='시작 시간'),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False, comment='종료 시간'),
    sa.Column('min_interval_seconds', sa.Integer(), nullable=True, comment='최소 간격 (초)'),
    sa.Column('max_interval_seconds', sa.Integer(), nullable=True, comment='최대 간격 (초)'),
    sa.Column('messages_generated', sa.Integer(), nullable=True, comment='생성된 메시지 수'),
    sa.Column('last_generated_at', sa.DateTime(timezone=True), nullable=True, comment='마지막 생성 시간'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='수정일시'),
    sa.ForeignKeyConstraint(['dispatch_id'], ['dispatches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_band_message_schedules_id'), 'band_message_schedules', ['id'], unique=False)
    op.create_table('band_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dispatch_id', sa.Integer(), nullable=False, comment='배차 ID'),
    sa.Column('message_content', sa.Text(), nullable=False, comment='생성된 메시지 내용'),
    sa.Column('message_type', sa.String(length=50), nullable=True, comment='메시지 타입'),
    sa.Column('is_sent', sa.Boolean(), nullable=True, comment='전송 여부 (수동 전송 확인)'),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True, comment='전송 일시'),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='생성 일시'),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True, comment='예약 전송 시간'),
    sa.Column('variation_seed', sa.Integer(), nullable=True, comment='메시지 변형 시드'),
    sa.ForeignKeyConstraint(['dispatch_id'], ['dispatches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_band_messages_id'), 'band_messages', ['id'], unique=False)
    op.create_table('dispatch_routes',
    sa.Column('dispatch_id', sa.Integer(), nullable=False, comment='배차 ID'),
    sa.Column('sequence', sa.Integer(), nullable=False, comment='경로 순서'),
    sa.Column('route_type', sa.Enum('GARAGE_START', 'PICKUP', 'DELIVERY', 'GARAGE_END', name='routetype'), nullable=False, comment='경로 유형'),
    sa.Column('order_id', sa.Integer(), nullable=True, comment='주문 ID'),
    sa.Column('location_name', sa.String(length=200), nullable=False, comment='위치명'),
    sa.Column('address', sa.String(length=500), nullable=False, comment='주소'),
    sa.Column('latitude', sa.Float(), nullable=False, comment='위도'),
    sa.Column('longitude', sa.Float(), nullable=False, comment='경도'),
    sa.Column('distance_from_previous_km', sa.Float(), nullable=True, comment='이전 지점 거리(km)'),
    sa.Column('duration_from_previous_minutes', sa.Integer(), nullable=True, comment='이전 지점 소요시간(분)'),
    sa.Column('estimated_arrival_time', sa.String(length=5), nullable=True, comment='예상 도착시간(HH:MM)'),
    sa.Column('estimated_work_duration_minutes', sa.Integer(), nullable=True, comment='예상 작업시간(분)'),
    sa.Column('estimated_departure_time', sa.String(length=5), nullable=True, comment='예상 출발시간(HH:MM)'),
    sa.Column('current_pallets', sa.Integer(), nullable=False, comment='현재 적재 팔레트 수'),
    sa.Column('current_weight_kg', sa.Float(), nullable=False, comment='현재 적재 중량(kg)'),
    sa.Column('notes', sa.Text(), nullable=True, comment='특이사항'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['dispatch_id'], ['dispatches.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicle_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('dispatch_id', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('altitude', sa.Float(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('heading', sa.Float(), nullable=True),
    sa.Column('temperature_celsius', sa.Float(), nullable=True),
    sa.Column('humidity_percent', sa.Float(), nullable=True),
    sa.Column('uvis_device_id', sa.String(length=100), nullable=True),
    sa.Column('uvis_timestamp', sa.DateTime(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('is_ignition_on', sa.Boolean(), nullable=True),
    sa.Column('battery_voltage', sa.Float(), nullable=True),
    sa.Column('fuel_level_percent', sa.Float(), nullable=True),
    sa.Column('odometer_km', sa.Float(), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['dispatch_id'], ['dispatches.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_locations_dispatch_id'), 'vehicle_locations', ['dispatch_id'], unique=False)
    op.create_index(op.f('ix_vehicle_locations_id'), 'vehicle_locations', ['id'], unique=False)
    op.create_index(op.f('ix_vehicle_locations_recorded_at'), 'vehicle_locations', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_vehicle_locations_vehicle_id'), 'vehicle_locations', ['vehicle_id'], unique=False)
    op.create_table('temperature_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('dispatch_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('temperature_celsius', sa.Float(), nullable=False),
    sa.Column('threshold_min', sa.Float(), nullable=True),
    sa.Column('threshold_max', sa.Float(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=True),
    sa.Column('notification_sent', sa.Boolean(), nullable=True),
    sa.Column('notification_channels', sa.String(length=200), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['dispatch_id'], ['dispatches.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['vehicle_locations.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_temperature_alerts_detected_at'), 'temperature_alerts', ['detected_at'], unique=False)
    op.create_index(op.f('ix_temperature_alerts_dispatch_id'), 'temperature_alerts', ['dispatch_id'], unique=False)
    op.create_index(op.f('ix_temperature_alerts_id'), 'temperature_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_temperature_alerts_is_resolved'), 'temperature_alerts', ['is_resolved'], unique=False)
    op.create_index(op.f('ix_temperature_alerts_vehicle_id'), 'temperature_alerts', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_temperature_alerts_vehicle_id'), table_name='temperature_alerts')
    op.drop_index(op.f('ix_temperature_alerts_is_resolved'), table_name='temperature_alerts')
    op.drop_index(op.f('ix_temperature_alerts_id'), table_name='temperature_alerts')
    op.drop_index(op.f('ix_temperature_alerts_dispatch_id'), table_name='temperature_alerts')
    op.drop_index(op.f('ix_temperature_alerts_detected_at'), table_name='temperature_alerts')
    op.drop_table('temperature_alerts')
    op.drop_index(op.f('ix_vehicle_locations_vehicle_id'), table_name='vehicle_locations')
    op.drop_index(op.f('ix_vehicle_locations_recorded_at'), table_name='vehicle_locations')
    op.drop_index(op.f('ix_vehicle_locations_id'), table_name='vehicle_locations')
    op.drop_index(op.f('ix_vehicle_locations_dispatch_id'), table_name='vehicle_locations')
    op.drop_table('vehicle_locations')
    op.drop_table('dispatch_routes')
    op.drop_index(op.f('ix_band_messages_id'), table_name='band_messages')
    op.drop_table('band_messages')
    op.drop_index(op.f('ix_band_message_schedules_id'), table_name='band_message_schedules')
    op.drop_table('band_message_schedules')
    op.drop_index(op.f('ix_vehicle_temperature_logs_tid_id'), table_name='vehicle_temperature_logs')
    op.drop_index(op.f('ix_vehicle_temperature_logs_id'), table_name='vehicle_temperature_logs')
    op.drop_index('idx_vehicle_temp_vehicle_id', table_name='vehicle_temperature_logs')
    op.drop_index('idx_vehicle_temp_tid', table_name='vehicle_temperature_logs')
    op.drop_index('idx_vehicle_temp_date_time', table_name='vehicle_temperature_logs')
    op.drop_index('idx_vehicle_temp_created', table_name='vehicle_temperature_logs')
    op.drop_table('vehicle_temperature_logs')
    op.drop_index(op.f('ix_vehicle_gps_logs_tid_id'), table_name='vehicle_gps_logs')
    op.drop_index(op.f('ix_vehicle_gps_logs_id'), table_name='vehicle_gps_logs')
    op.drop_index('idx_vehicle_gps_vehicle_id', table_name='vehicle_gps_logs')
    op.drop_index('idx_vehicle_gps_tid', table_name='vehicle_gps_logs')
    op.drop_index('idx_vehicle_gps_date_time', table_name='vehicle_gps_logs')
    op.drop_index('idx_vehicle_gps_created', table_name='vehicle_gps_logs')
    op.drop_table('vehicle_gps_logs')
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_dispatches_dispatch_number'), table_name='dispatches')
    op.drop_index(op.f('ix_dispatches_dispatch_date'), table_name='dispatches')
    op.drop_table('dispatches')
    op.drop_index(op.f('ix_vehicles_code'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_uvis_api_logs_id'), table_name='uvis_api_logs')
    op.drop_index('idx_uvis_log_type', table_name='uvis_api_logs')
    op.drop_index('idx_uvis_log_created', table_name='uvis_api_logs')
    op.drop_table('uvis_api_logs')
    op.drop_index(op.f('ix_uvis_access_keys_id'), table_name='uvis_access_keys')
    op.drop_index('idx_uvis_access_key_expires', table_name='uvis_access_keys')
    op.drop_index('idx_uvis_access_key_active', table_name='uvis_access_keys')
    op.drop_table('uvis_access_keys')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_purchase_orders_id'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index(op.f('ix_notices_id'), table_name='notices')
    op.drop_table('notices')
    op.drop_index(op.f('ix_drivers_code'), table_name='drivers')
    op.drop_table('drivers')
    op.drop_index(op.f('ix_clients_code'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_band_chat_rooms_id'), table_name='band_chat_rooms')
    op.drop_table('band_chat_rooms')
    # ### end Alembic commands ###
